baseURL = "https://parsarajaee.ir/"
languageCode = "fa"
title = "وبلاگ پارسا رجائی"
theme = "PaperMod"
defaultContentLanguage = "fa"

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true

[related]
threshold = 80
includeNewer = true

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name = "tags"
weight = 80

[menu]
  [[menu.main]]
    identifier = "about"
    name = "درباره من"
    url = "/about/"
    weight = 10

[params]
  disqusShortname = ""

[params.assets]
  customCSS = ["css/custom.css"]

[params.giscus]
  enable = true
  repo = "Parsa-Rajaee/myblog"
  repoID = "R_kgDORTKYTg"
  category = "General"
  categoryID = "DIC_kwDORTKYTs4C2vgv"
  mapping = "pathname"
  reactionsEnabled = "1"
  theme = "light"

